---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yangxiao.
--- DateTime: 2019/1/10 10:53
---

local events = require "kong.core.events"
local cache = require "kong.tools.database_cache"

local function invalidate_on_update(message_t)
    if message_t.collection == "quota" then
        -- delete cache when update quota
        cache.delete("quota."..message_t.entity.custom_id)
    end
end

local function invalidate_on_create(message_t)
    if message_t.collection == "quota" then
        -- create cache when create quota
        cache.set("quota."..message_t.entity.custom_id,message_t.entity.status)
    end
end

return {
    [events.TYPES.ENTITY_UPDATED] = function(message_t)
        invalidate_on_update(message_t)
    end,
    [events.TYPES.ENTITY_CREATED] = function(message_t)
        invalidate_on_create(message_t)
    end
}