---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yangxiao.
--- DateTime: 2019/1/8 14:31
--- auth_server_url default empty mean auto to all request
---

return {
    no_consumer = true,
    fields = {
        open_debug = {type = "number", default = 0},
        white_list = {type = "array",require = false}
    }
}